version: '3.7'

services:
  notify:
    image: ghcr.io/k0in/notify:latest
    restart: unless-stopped
    volumes:
      # this is a example how your settings fike coud look like
      # see the install docs for more info
      - ./prod.env:/usr/app/app.env:ro
      # ./users:/usr/app/data # this is an example how you can persist your user

    ports:
      - "8787:8787" 
      # be aware that notify only runs on http but you will need https for frontend to work
      # put it behind a traefik or nginx to secure it 
