name = "notify_app"
type = "javascript"
zone_id = ""
account_id = ""
workers_dev = true

kv_namespaces = [
    { binding = "NOTIFY_USERS", id = "614c593c1c0d4f51a3b40864e61bc4e0" }
]

[build]
command = "npm install && cd frontend && npm install && cd .. && npm run build_all"

[build.upload]
format = "service-worker"

# See doc/wrangler.md to learn more about the wrangler section
[vars]
VAPID_SERVER_KEY = "{\"crv\":\"P-256\",\"d\":\"MM3IEY73Br5_Hdtfknab6QIXqCHXv7S5cZrlD3lrjuk\",\"ext\":true,\"key_ops\":[\"sign\"],\"kty\":\"EC\",\"x\":\"YNEmMB5QyQULW4WepHQvn5WWrBXpHGFB51eJ3oJj3k4\",\"y\":\"NU3NCQI82-WvNWc2vc9HV8YOIAC9VsMrMhJhi3XS8MQ\"}"
SUB = "admin@example.com"
SERVERPWD = "" # "" = no pw
CORS_ORIGIN = "*" # "" = no cors
SERVE_FRONTEND = true

# [secrets]
# VAPID_SERVER_KEY
# SERVERPWD


[site]
bucket = "frontend/build"
entry-point = "."

[miniflare]
kv_persist = "./data/"
