name = "notify_app"
type = "javascript"
zone_id = ""
account_id = ""
workers_dev = true

kv_namespaces = [
    { binding = "NOTIFY_USERS", id = "00000000000000000000000000000000" } # your kv id here
]

[build]
command = "npm install && cd frontend && npm install && cd .. && npm run build_all"

[build.upload]
format = "service-worker"

# See doc/wrangler.md to learn more about the wrangler section
# [vars]
# VAPID_SERVER_KEY = "{\"crv\":\"P-256\",\"d\":\"MM3IEY73Br5_Hdtfknab6QIXqCHXv7S5cZrlD3lrjuk\",\"ext\":true,\"key_ops\":[\"sign\"],\"kty\":\"EC\",\"x\":\"YNEmMB5QyQULW4WepHQvn5WWrBXpHGFB51eJ3oJj3k4\",\"y\":\"NU3NCQI82-WvNWc2vc9HV8YOIAC9VsMrMhJhi3XS8MQ\"}"
# SUB = "admin@example.com"
# SERVERPWD = "" # "" = no pw
# AUTHPWD= "" # "" = no pw
# CORS_ORIGIN = "*" # "" = no cors
# SERVE_FRONTEND = true

# [secrets]
# VAPID_SERVER_KEY
# SERVERPWD
# AUTHPWD


[site]
bucket = "frontend/build"
entry-point = "."

[miniflare]
kv_persist = "./data/"

[env.demo]
kv_namespaces = [
    { binding = "NOTIFY_USERS", id = "5df92089b8ea45e68592058740136ce1" }
]

[env.demo.vars]
VAPID_SERVER_KEY = "{\"crv\":\"P-256\",\"d\":\"MM3IEY73Br5_Hdtfknab6QIXqCHXv7S5cZrlD3lrjuk\",\"ext\":true,\"key_ops\":[\"sign\"],\"kty\":\"EC\",\"x\":\"YNEmMB5QyQULW4WepHQvn5WWrBXpHGFB51eJ3oJj3k4\",\"y\":\"NU3NCQI82-WvNWc2vc9HV8YOIAC9VsMrMhJhi3XS8MQ\"}"
SUB = "thisk0in@gmail.com"
SERVERPWD = ""
AUTHPWD = ""
CORS_ORIGIN = "*"
SERVE_FRONTEND = true
