version: '3.7'

services:
  notify:
    # build from source
    build:
      context: ../
      dockerfile: Dockerfile
    # or use our image
    # image: ghcr.io/k0in/notify:latest

    restart: unless-stopped
    ports:
      - "8787:80" 

    environment:
      - PORT=80
      - VAPID_KEY=eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwiYWxnIjoiRVMyNTYiLCJ4IjoiUV92WlVXUExOUlFMRnU5QWRNaGRDQlFpY1FKamxYajVHZ2lwY19BS1E5USIsInkiOiJILXlDUF9hZ3FzRmpGMmgtZ2dNTTdVT1UxdktJN1JTcU1XSVhfZjBJekhnIiwiZCI6IjVXdzg1TnFxN09lY0pyaDN5MDl6a1JLWWR3TEhUVTVObjlNZUNqMkh6Y2MiLCJrZXlfb3BzIjpbInNpZ24iXSwiZXh0Ijp0cnVlfQ==
      - SUB=mailto:admin@example.com
      - SENDKEY=password123 # password needed to send notifications to the instance
    