name = "backend"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

kv_namespaces = [
    { binding = "NOTIFY_USERS", id = "" }
]

[build]
command = "npm install && npm run build_all"

[build.upload]
format = "service-worker"

[vars] # here are some default values please overwrite them in your config!
VAPID_SERVER_KEY = "{\"crv\":\"P-256\",\"d\":\"MM3IEY73Br5_Hdtfknab6QIXqCHXv7S5cZrlD3lrjuk\",\"ext\":true,\"key_ops\":[\"sign\"],\"kty\":\"EC\",\"x\":\"YNEmMB5QyQULW4WepHQvn5WWrBXpHGFB51eJ3oJj3k4\",\"y\":\"NU3NCQI82-WvNWc2vc9HV8YOIAC9VsMrMhJhi3XS8MQ\"}"
SUB = "admin@example.com"
SERVERPWD = "" # default = no pw
CORS_ORIGIN = "" # no cors
SERVE_FRONTEND = true

# you have to define these secrets (see install instructions in doc/install.md)
# [secrets]
# VAPID_SERVER_KEY
# SERVERPWD


[site]
bucket = "frontend/build"
entry-point = "."
