name: Build and publish demo to deno deploy

on:
  push:
    branches:
      - "main"
      - '*'

jobs:
  build-and-deploy-worker:
    environment: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install make
        run: sudo apt update && sudo apt install make -y

      - name: build deploy folder
        run: make deploy

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: notify-demo
          entrypoint: deploy.ts
          root: ./deploy
          import-map: deno.json