name: Build and publish demo to Cloudflare

on:
    push:
        branches:
            - 'main'

jobs:
    build-and-deploy-worker:        
        environment: deploy
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./app/
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Deploy app to cloudflare
              uses: cloudflare/wrangler-action@1.3.0
              with:
                apiToken: ${{ secrets.CF_TOKEN }}
                environment: 'demo'
                workingDirectory: 'app'
